server:
  port: 9090

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Ajinkyaw1999/config.git
          name: ${spring.application.name},eshop
          username: Ajinkyaw1999
          password: '@swami99'
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka